### ISSUE TITLE
Not an Issue , Question  EFI

### ISSUE THREAD

**Issue by tryitagain** [Lorys89/Lorys89#1]
Hi Lorys89, I am trying your EFI 7210 ( https://mega.nz/file/FRVlUTzJ#fTYUuWl7dEupIOPu66PjoWaY4BiXyUsbXh8ItbPDQEU)
On Dell 2 in 1 7200 I7 8665U OC 1.01 Sonoma . All works, only sleep problem :  wake up screen will change color ( kind like monochrome and all vertical color  ). But The extended monitor works fine, only laptop screen has a problem. Any suggestion how to fix it ? btw  on Sequoia have same behaviour plus no WIFI . Thanks

**Comment by Lorys89** [comment]
Write here https://macos86.it/topic/6466-dell-latitude-7210-2-in-1/
